import { v4 as uuidv4 } from "uuid";
function evolette() {
    return [
        {
            number: "1",
            name: "Pánik",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette feat Táborosi István",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "4:00",
            audio: "https://taborosidesign.com/evolette/001.mp3",
            videourl: "https://www.youtube.com/watch?v=2S7Vtsdz0RI",
            id: uuidv4(),
            active: true,
            video: true,
        },
        {
            number: "2",
            name: "Nem Ismersz Igazán",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "2:34",
            audio: "https://taborosidesign.com/evolette/002.mp3",
            id: uuidv4(),
            active: false,
            video: false,
        },
        {
            number: "3",
            name: "Árnyékként",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette feat Nixon",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "4:14",
            audio: "https://taborosidesign.com/evolette/003.mp3",
            id: uuidv4(),
            active: false,
            video: false,
        },
        {
            number: "4",
            name: "Régi Naplóm",
            cover: "https://taborosidesign.com/evolette/artist_cover_reginaplom.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "3:07",
            audio: "https://taborosidesign.com/evolette/004.mp3",
            videourl: "https://www.youtube.com/watch?v=s8afjZ46GvI",
            id: uuidv4(),
            active: false,
            video: true,
        },
        {
            number: "5",
            name: "Összedőlt Vár",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "3:25",
            audio: "https://taborosidesign.com/evolette/005.mp3",
            id: uuidv4(),
            active: false,
            video: false,
        },
        {
            number: "6",
            name: "S.N.A.F",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "3:29",
            audio: "https://taborosidesign.com/evolette/006.mp3",
            id: uuidv4(),
            active: false,
            video: false,
        },
        {
            number: "7",
            name: "Eső",
            cover: "https://taborosidesign.com/evolette/artist_cover_eso.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "3:11",
            audio: "https://taborosidesign.com/evolette/007.mp3",
            videourl: "https://www.youtube.com/watch?v=zuVv_Q_BykU",
            id: uuidv4(),
            active: false,
            video: true,
        },
        {
            number: "8",
            name: "Momento",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "3:21",
            audio: "https://taborosidesign.com/evolette/008.mp3",
            id: uuidv4(),
            active: false,
            video: false,
        },
        {
            number: "9",
            name: "Addikt",
            cover: "https://taborosidesign.com/evolette/artist_cover_addikt.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "3:10",
            audio: "https://taborosidesign.com/evolette/009.mp3",
            videourl: "https://www.youtube.com/watch?v=n8le8Rt_Mcs",
            id: uuidv4(),
            active: false,
            video: true,
        },
        {
            number: "10",
            name: "539",
            cover: "https://taborosidesign.com/evolette/artist_cover.jpg",
            artist: "Evolette",
            album: "Pánik",
            relase: "Sep 30, 2020",
            duration: "4:03",
            audio: "https://taborosidesign.com/evolette/010.mp3",
            id: uuidv4(),
            active: false,
            video: false,
        },
    ]
}

export default evolette;